import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-zinc-200 bg-white/60 backdrop-blur-sm dark:bg-black/60 dark:border-zinc-800">
          <div className="mx-auto flex max-w-5xl items-center justify-between p-4">
            <nav className="flex gap-4">
              <Link href="/" className="text-sm font-medium">Home</Link>
              <Link href="/home" className="text-sm font-medium">Home (page)</Link>
              <Link href="/awareness" className="text-sm font-medium">Awareness</Link>
            </nav>
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
